apps/ssl_cert/urls.py
from django.urls import path
from . import views
from . import custom_domain_menu_views

app_name = 'ssl_cert'
urlpatterns = [
    path('domain_list/', views.domain_list, name="domain_list"),
    path('create/', views.CreateSSLCertView.as_view(), name="create"),
    path('batch_create/', views.BatchCreateSslCertView.as_view(), name="batch_create"),
    path('upload_ssl_cert/', views.UploadSSLCertView.as_view(), name="upload_ssl_cert"),
    path('view_ssl_cert/', views.ViewSSLCertView.as_view(), name="view_ssl_cert"),
    path('download_file/', views.DownloadFileView.as_view(), name="download_file"),
    path('update_ssl_cert/', views.UpdateSSLCertView.as_view(), name="update_ssl_cert"),
    path('disable_ssl_cert/', views.DisableSSLCertView.as_view(), name="disable_ssl_cert"),
    path('delete_ssl_cert/', views.DeleteSSLCertView.as_view(), name="delete_ssl_cert"),
    path('sync_sub_domains/', views.SyncSubDomainView.as_view(), name="sync_sub_domains"),
    path('sub_domains/', views.SubDomainsView.as_view(), name="sub_domains"),
    path('dns/', views.DnsView.as_view(), name="dns"),
    path('to_email/', views.ToEmailView.as_view(), name="to_email"),
    path('source_ip/', views.SourceIPView.as_view(), name="source_ip"),
    path('send_ssl_cert_to_email/', views.SendSSLCertView.as_view(), name="send_ssl_cert_to_email"),
    path('add_record/', views.AddRecordView.as_view(), name="add_record"),
    path('modify_record/', views.ModifyRecordView.as_view(), name="modify_record"),
    path('set_record_status/', views.SetRecordStatusView.as_view(), name="set_record_status"),
    path('delete_record/', views.DeleteRecordView.as_view(), name="delete_record"),

    path('check_domain_status/', views.CheckDomainStatusView.as_view(), name="check_domain_status"),

    path('custom_domain/', custom_domain_menu_views.CustomDomainViews.as_view(), name="custom_domain"),
    path('custom_domain_list/', custom_domain_menu_views.custom_domain_list, name="custom_domain_list"),
    path('add_custom_domain/', custom_domain_menu_views.AddCustomDomainView.as_view(), name="add_custom_domain"),
    path('delete_custom_domain/', custom_domain_menu_views.DeleteCustomDomainView.as_view(),
         name="delete_custom_domain"),
    path('to_email_custom_domain/', custom_domain_menu_views.CustomDomainToEmailView.as_view(),
         name="to_email_custom_domain"),
]

new_ssl_cert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from ssl_cert.views import IndexView
# from users import views

urlpatterns = [
    path('ssl-cert-admin/', admin.site.urls),

    path('index/', IndexView.as_view(), name="index"),
    path('', RedirectView.as_view(url='index/')),
    path('ssl/', include("ssl_cert.urls")),
    path('users/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    # path('ajax_captcha/', views.ajax_captcha, name='ajax_captcha'),
]

apps/ssl_cert/models.py
from django.db import models
import datetime

from apps.ssl_cert.config import dns_api_mode


# Create your models here.


class Domain(models.Model):
    """
    域名
    """
    status_list = (
        ("valid", '有效'),
        ("invalid", "无效"),
        ("pending", "创建中"),
        ("failed", "失败"),
    )

    dns_list = [(key.lower(), key) for key in dns_api_mode.keys()]
    """
    dns_list = (
        ("dnspod", "DNSPod"),
        ("cloudflare", "CloudFlare"),
        ("aliyun", "Aliyun"),
    )
    """

    domain = models.CharField(verbose_name='域名', max_length=100, db_index=True, unique=True)
    extensive_domain = models.BooleanField(verbose_name="泛域名")
    status = models.CharField(verbose_name="状态", max_length=20, choices=status_list, default="valid")
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    start_date = models.DateTimeField(verbose_name='开始日期', default=datetime.datetime.now)
    expire_date = models.DateTimeField(verbose_name='过期日期',
                                       default=(datetime.datetime.now() + datetime.timedelta(days=90)))
    dns = models.CharField(verbose_name="DNS解析商", max_length=20, choices=dns_list)
    dns_account = models.CharField(verbose_name="DNS API账号", max_length=150)
    comment = models.TextField(verbose_name="备注", max_length=200, null=True, blank=True)
    source_ip = models.CharField(verbose_name="源站IP", max_length=15, null=True, blank=True)

    class Meta:
        # 数据库中生成的表名称 默认 app名称 + 下划线 + 类名
        # db_table = "domain_info"
        ordering = ("-id",)
        # 定义在管理后台显示的名称
        verbose_name = '域名'
        # 指定复数时的名称(去除复数的s)
        verbose_name_plural = verbose_name

    def __str__(self):
        return F"{self.domain} {self.dns}"

    # 还没用到此方法
    def get_time_diff(self):
        """过期时间减去当前时间得到剩余天数"""
        now = datetime.datetime.now()
        return (self.expire_date - now).days


class ToEmail(models.Model):
    """
    接收证书的邮箱
    """
    email = models.EmailField(verbose_name="邮箱")
    domain = models.ForeignKey("Domain", on_delete=models.CASCADE, blank=True, null=True)
    custom_domain = models.ForeignKey("CustomDomain", on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.email

    class Meta:
        ordering = ("-id",)
        verbose_name = "通知邮箱"
        verbose_name_plural = verbose_name


class SSLCertContent(models.Model):
    """
    域名证书
    """
    cert_content = models.TextField(verbose_name="证书")
    key_content = models.TextField(verbose_name="key")
    domain = models.OneToOneField("Domain", on_delete=models.CASCADE)

    class Meta:
        ordering = ("-id",)
        # 定义在管理后台显示的名称
        verbose_name = '证书内容'
        # 指定复数时的名称(去除复数的s)
        verbose_name_plural = verbose_name

    def __str__(self):
        return F"{self.domain_id}"


class SubDomains(models.Model):
    """
    子域名
    """
    protocol_type = (
        ("http", 'http'),
        ("https", "https"),
    )
    record_type_list = (
        ("A", 'A'),
        ("CNAME", "CNAME"),
        ("AAAA", 'AAAA'),
        ("MX", "MX"),
        ("NS", "NS"),
        ("SRV", 'SRV'),
        ("CAA", "CAA"),
        ("explicit_URL", "explicit_URL"),
        ("implicit_URL", "implicit_URL"),
    )
    protocol = models.CharField(verbose_name="协议", max_length=5, choices=protocol_type)
    sub_domain = models.CharField(verbose_name="子域名", max_length=253, db_index=True)
    record_type = models.CharField(verbose_name="记录类型", max_length=20, choices=record_type_list)
    record_value = models.CharField(verbose_name="记录值", max_length=198)
    start_date = models.DateTimeField(verbose_name="开始日期", blank=True, null=True)
    expire_date = models.DateTimeField(verbose_name="过期日期", blank=True, null=True)
    comment = models.CharField(verbose_name="备注", max_length=50, blank=True, null=True)
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE, verbose_name="主域名")

    class Meta:
        verbose_name = "子域名"
        verbose_name_plural = verbose_name


class SubSyncLimit(models.Model):
    """
    子域名同步频率限制
    每次同步间隔 2 分钟
    """
    user = models.CharField(verbose_name="用户名", max_length=50)
    domain = models.CharField(verbose_name="域名", max_length=100)
    sync_time = models.DateTimeField(verbose_name="同步时间", default=datetime.datetime.now)

    class Meta:
        verbose_name = "子域名同步频率限制"
        verbose_name_plural = verbose_name


class CustomDomain(models.Model):
    """
    自定义域名
    """
    domain = models.CharField(verbose_name="域名", max_length=50)
    source_ip = models.GenericIPAddressField(verbose_name="源站IP")
    start_date = models.DateTimeField(verbose_name='开始日期', blank=True, null=True)
    expire_date = models.DateTimeField(verbose_name='过期日期', blank=True, null=True)

    class Meta:
        verbose_name = "自定义域名"
        verbose_name_plural = verbose_name

    def __str__(self):
        return F"{self.domain} -> {self.source_ip}"

apps/ssl_cert/views.py
import os
import logging
import time
import shutil
import re
from threading import Thread
from urllib3.contrib import pyopenssl as reqs
import OpenSSL
from datetime import datetime, timedelta
from django.shortcuts import render
from django.views.generic.base import View, TemplateView
from django.views.generic import ListView
from django.http import JsonResponse, HttpResponse, StreamingHttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import QueryDict
from .models import Domain, SSLCertContent, SubDomains, SubSyncLimit, ToEmail
from .config import dns_api_mode, CERT_DIR
from res.ssl_cert import SSLCert
from apps.mixin import LoginRequiredMixin
from res.acme import Acme
from res.domain import DomainClassify
from res.email_table.send_ssl_cert_email_table import email_table
from res.custom_send_email import send_email

# Create your views here.

log = logging.getLogger('django')

User = get_user_model()


class IndexView(LoginRequiredMixin, TemplateView):
    """
    首页
    """
    template_name = "ssl_cert/index.html"


@login_required
def domain_list(request):
    """
    域名列表
    """
    page = request.GET.get('page')
    limit = request.GET.get('limit', 20)
    search_content = request.GET.get('searchContent', "")
    # 如果是管理员账号，返回全部域名，如果是普通账号，返回授权的域名
    # TODO 此功能未启用
    # user_obj = get_object_or_404(User, username=request.user)
    # if user_obj.is_superuser:
    #     query = Domain.objects.filter(Q(domain__contains=search_content) | Q(dns__contains=search_content)).order_by(
    #         '-id')
    # else:
    #     query = user_obj.domain.filter(Q(domain__contains=search_content) | Q(dns__contains=search_content)).order_by(
    #         '-id')
    query = Domain.objects.filter(Q(domain__contains=search_content) | Q(dns__contains=search_content)).order_by(
        '-id')
    paginator = Paginator(query, limit)
    count = query.count()

    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # 如果请求的页数不是整数，返回第一页。
        contacts = paginator.page(1)
    except EmptyPage:
        # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        contacts = paginator.page(paginator.num_pages)

    data = {
        "code": 0,
        "msg": "",
        "count": count,
        "data": list(contacts.object_list.values()),
    }

    return JsonResponse(data)


class CreateSSLCertView(LoginRequiredMixin, View):
    """
    创建ssl证书
    """

    def get(self, request):
        dns_list = [item[1] for item in Domain.dns_list]
        return render(request, 'ssl_cert/create_ssl_cert.html', {"dns_list": dns_list})

    def post(self, request):
        domain = request.POST.get("domain")
        extensive_domain = True if request.POST.get("extensiveDomainOpen") == "on" else False
        dns = request.POST.get("selectDns")
        comment = request.POST.get("comment")
        dns_account = {}
        for i, k in enumerate(dns_api_mode[dns]):
            dns_account[k] = request.POST.get("dnsAccount" + str(i + 1))

        if Domain.objects.filter(domain=domain).exists():
            return JsonResponse({"status": "failed", "message": "域名已存在", "form": request.POST})

        Domain(
            domain=domain,
            extensive_domain=extensive_domain,
            status="pending",
            dns=dns,
            dns_account=dns_account,
            comment=comment,
        ).save()

        # 创建证书
        ssl_cert = SSLCert(domain, extensive_domain, dns, dns_account)
        t = Thread(target=ssl_cert.create)
        t.daemon = True
        t.start()

        return JsonResponse({"status": "success"})


class BatchCreateSslCertView(LoginRequiredMixin, View):
    """
    批量创建ssl证书: 校验部分
    """

    def post(self, request):
        multiple_domain = request.POST.get('batchCreateSSL').split("\n")
        if len(multiple_domain) > 50:
            log.error("batch create ssl: content too long")
            return JsonResponse({"status": "max_limit", "message": "content too long"})
        new_multiple_domain = []
        log.info(F"batch create ssl cert: {multiple_domain}")
        for line in multiple_domain:
            if not line: continue
            line = line.strip()
            if len(line.split(',')) < 5 or len(line.split(',')) >= 7 or line.split(',')[4] not in ("on", "off"):
                log.error(F"Format incorrect: {line}")
                return JsonResponse({"status": "incorrect", "message": line})
            if Domain.objects.filter(domain=line.split(',')[0].strip()).exists():
                log.error(F"domain exist: {line.split(',')[0]}")
                return JsonResponse({"status": "exist", "message": line.split(',')[0]})
            if not dns_api_mode.get(line.split(',')[1].strip().lower()):
                log.error(F"dns not exist: {line.split(',')[0]} {line.split(',')[1]}")
                return JsonResponse({"status": "not exist", "message": line.split(',')[1]})

            new_multiple_domain.append(line.split(','))

        t = Thread(target=exec_batch_create, args=(new_multiple_domain,))
        t.daemon = True
        t.start()
        return JsonResponse({"status": "success"})


# @login_required
def exec_batch_create(domain_list: list):
    """
    批量创建ssl证书: 执行创建部分
    """
    # thread_list = []
    for item in domain_list:
        print(item)
        dns_account = {}
        for i, k in enumerate(dns_api_mode[item[1]]):
            dns_account[k] = item[i + 2].strip()
        extensive_domain = True if item[4] == "on" else False

        # 保存域名
        Domain(
            domain=item[0].strip(),
            extensive_domain=extensive_domain,
            status="pending",
            dns=item[1].strip().lower(),
            dns_account=dns_account,
            comment=item[-1] if len(item) == 6 else "",
        ).save()

        # 创建证书
        ssl_cert = SSLCert(item[0], extensive_domain, item[1].lower(), dns_account)
        t = Thread(target=ssl_cert.create)
        t.start()
        t.join()
        # thread_list.append(t)
        time.sleep(2)

    # for t in thread_list:
    #     t.join()


def parse_ssl_cert(cert_content):
    """
    解析上传的证书
    """
    try:
        x509 = reqs.OpenSSL.crypto.load_certificate(reqs.OpenSSL.crypto.FILETYPE_PEM, cert_content)
        start_date = datetime.strptime(x509.get_notBefore().decode()[0:-1], '%Y%m%d%H%M%S')
        expire_date = datetime.strptime(x509.get_notAfter().decode()[0:-1], '%Y%m%d%H%M%S')
        domain_list = reqs.get_subj_alt_name(x509)

        domain = None
        extensive_domain = False
        domain_list = [i[1] for i in domain_list]
        for d in domain_list:
            if "*" in d:
                extensive_domain = True
                domain = ''.join(d.split('*.'))
            else:
                domain = d

        return domain, extensive_domain, start_date, expire_date
    except OpenSSL.crypto.Error:
        return None, False, False, False


def save_cert_to_file(domain, cert_content, key_content):
    """
    将上传的证书保存在本地文件中
    """
    if not os.path.isdir(os.path.join(CERT_DIR, domain)):
        os.mkdir(os.path.join(CERT_DIR, domain))

    cert_file = os.path.join(CERT_DIR, domain, "fullchain.cer")
    key_file = os.path.join(CERT_DIR, domain, "{}.key".format(domain))

    with open(cert_file, 'w') as cf, open(key_file, 'w') as kf:
        cf.write(cert_content + "\n")
        kf.write(key_content + "\n")
        log.info(F"The contents of the certificate are saved in the file: {domain}")


def save_cert_to_db(domain, extensive_domain, start_date, expire_date, dns, dns_account, comment, cert_content,
                    key_content):
    """
    将上传的证书保存在数据库中
    """
    domain_obj = Domain.objects.create(
        domain=domain,
        extensive_domain=extensive_domain,
        status="valid",
        start_date=start_date,
        expire_date=expire_date,
        dns=dns,
        dns_account=dns_account,
        comment=comment,
    )

    SSLCertContent.objects.create(
        cert_content=cert_content,
        key_content=key_content,
        domain=domain_obj
    )

    log.info(F"The certificate content has been saved in the database: {domain}")


from res.dns_api.aliyun import ALIYUN
from res.dns_api.cloudflare import CLOUDFLARE
from res.dns_api.dnspod import DNSPOD
import random
import string


def verify_account(dns, domain, account):
    """
    验证上传证书时提交的账号是否可以使用
    验证方式:
        添加txt记录类型
        获取记录列表
        匹配添加的txt记录
        删除添加的txt记录
    """
    dns_list = [ALIYUN, CLOUDFLARE, DNSPOD]  # 此变量没有用到
    random_value = ''.join(random.sample(string.ascii_letters + string.digits, 16))
    cls = eval(dns.upper())
    obj = cls(domain, account)
    sub_domain = F"verify_domain_{''.join(random.sample(string.ascii_letters + string.digits, 8))}".lower()
    log.info(F"verify [{domain} - {dns}] account: add record [{sub_domain}]")
    result = obj.add_record(sub_domain, "TXT", "默认", random_value)
    if result:
        time.sleep(1)
        result = obj.delete_record(sub_domain)
        log.info(F"verify [{domain} - {dns}] account: del record [{sub_domain}]")
        return result


class UploadSSLCertView(LoginRequiredMixin, View):
    """
    上传证书
    """

    def get(self, request):
        dns_list = [item[1] for item in Domain.dns_list]
        return render(request, 'ssl_cert/upload_ssl_cert.html', context={"dns_list": dns_list})

    def post(self, request):
        dns = request.POST.get("selectDns")
        dns_account = {}
        for i, k in enumerate(dns_api_mode[dns]):
            dns_account[k] = request.POST.get("dnsAccount" + str(i + 1)).strip()
        cert_content = request.POST.get("cert")
        key_content = request.POST.get("private-key")
        comment = request.POST.get("comment")

templates/ssl_cert/dns.html
{% extends 'base-menu.html' %}

{% load static %}

{% block content %}
    <input hidden name="domain" value="{{ domain }}" id="domainInput">
    <input hidden name="dns" value="{{ dns }}" id="dnsInput">

    <div class="layui-container">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="fly-panel" style="min-height: 600px">
                    <div class="fly-panel-title">
                        <h3 style="display: inline">域名: {{ domain }}</h3>
                        <div class="layui-inline" style="float: right">
                            <button type="button" class="layui-btn layui-btn-sm layui-btn-radius" id="addRecord">
                                添加记录
                            </button>
                        </div>
                    </div>
                    <div class="fly-panel-main">
                        <table class="layui-table" id="dnsRecordTable">
                            <colgroup>
                                <col width="40">
                                <col>
                                <col width="100">
                                <col width="100">
                                <col>
                                <col width="100">
                                <col width="60">
                                <col width="60">
                                <col width="140">
                            </colgroup>
                            <thead>
                            <tr>
                                <th style="text-align: center">ID</th>
                                <th style="text-align: center">主机记录</th>
                                <th style="text-align: center">记录类型</th>
                                <th style="text-align: center">解析线路</th>
                                <th style="text-align: center">记录值</th>
                                <th style="text-align: center">MX优先级</th>
                                <th style="text-align: center">TTL（秒）</th>
                                <th style="text-align: center">状态</th>
                                <th style="text-align: center">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {#<tr style="text-align: center">#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>无</td>#}
                            {#    <td>#}
                            {#        <div class="layui-btn-group">#}
                            {#            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">修改#}
                            {#            </button>#}
                            {#            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">删除#}
                            {#            </button>#}
                            {#            <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">暂停#}
                            {#            </button>#}
                            {#        </div>#}
                            {#    </td>#}
                            {#</tr>#}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $("#menuIndex").addClass("layui-this");
    </script>

    <script>
        layui.use('layer', function () {
            var layer = layui.layer;

            // 加载子域名
            $(function () {
                layer.load(0, {shade: false});          // loading 加载层。0代表加载的风格，支持0-2
                var domain = $("#domainInput").val();
                var url = "{% url 'ssl_cert:dns' %}";
                var data = {
                    "domain": domain,
                    "csrfmiddlewaretoken": "{{ csrf_token }}",
                };
                $.post(url, data, function (result) {
                    layer.closeAll('loading');          // 关闭loading 加载层
                    if (result["record_list"].length > 0) {
                        var record_list = result["record_list"];
                        for (var i = 0; i < record_list.length; i++) {
                            var disableOrEnable = record_list[i]["status"] === "正常" ? "暂停" : "启用";
                            var line = record_list[i]["line"] ? record_list[i]["line"] : "";
                            var mx = record_list[i]["mx"] === "0" ? "-" : record_list[i]["mx"];

                            var disableButton = "";
                            var dns = $("#dnsInput").val();
                            if (dns !== "cloudflare") {
                                var disableButton = '<button type="button" class="layui-btn layui-btn-primary layui-btn-xs" onclick="setRecordStatus(this);">' + disableOrEnable + '</button>';
                            }
                            var tr = '<tr style="text-align: center">'
                                + "<td>" + (parseInt(i) + 1) + "</td>"
                                + "<td>" + record_list[i]["name"].split("." + domain)[0] + "</td>"
                                + "<td>" + record_list[i]["type"] + "</td>"
                                + "<td>" + line + "</td>"
                                + "<td>" + record_list[i]["value"] + "</td>"
                                + "<td>" + mx + "</td>"
                                + "<td>" + record_list[i]["ttl"] + "</td>"
                                + "<td>" + record_list[i]["status"] + "</td>"
                                + '<td>' + '<div class="layui-btn-group">'
                                + '<button type="button" class="layui-btn layui-btn-primary layui-btn-xs" onclick="modifyRecord(this);">修改</button>'
                                + disableButton
                                + '<button type="button" class="layui-btn layui-btn-primary layui-btn-xs" onclick="deleteRecord(this);">删除</button>'
                                + '</div>' + '</td>' + '</tr>';

                            // 在table最后面添加一行
                            $("#dnsRecordTable").append(tr);
                        }
                    } else {
                        var tr = '<tr style="text-align: center">' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>无</td>' +
                            '<td>' +
                            '    <div class="layui-btn-group">' +
                            '        <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">修改</button>' +
                            '        <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">暂停</button>' +
                            '        <button type="button" class="layui-btn layui-btn-primary layui-btn-xs">删除</button>' +
                            '    </div>' +
                            '</td>' + '</tr>';
                        $("#dnsRecordTable").append(tr);
                    }
                })
            });
        });
    </script>
    <script>
        // 添加记录
        $("#addRecord").click(function () {
            var domain = $("#domainInput").val();
            layer.open({
                type: 2,
                title: '添加记录',
                shadeClose: true,
                maxmin: true,
                area: ['550px', '450px'],
                content: ["{% url 'ssl_cert:add_record' %}?domain=" + domain],
                end: function () {
                    window.location.reload();
                },
            })
        });

        // 修改记录
        function modifyRecord(obj) {
            var thisObj = $(obj);
            var domain = $("#domainInput").val();
            var trObj = thisObj.parent().parent().parent();
            var name = trObj.find("td:eq(1)").text();       // eq()索引是从0开始计算
            var type = trObj.find("td:eq(2)").text();
            var line = trObj.find("td:eq(3)").text();
            var value = trObj.find("td:eq(4)").text();
            var mx = trObj.find("td:eq(5)").text();
            var ttl = trObj.find("td:eq(6)").text();

            layer.open({
                type: 2,
                title: '修改记录',
                shadeClose: true,
                maxmin: true,
                area: ['550px', '450px'],
                content: ["{% url 'ssl_cert:modify_record' %}?domain=" + domain + "&name=" + name + "&type=" + type + "&line=" + line + "&value=" + value + "&mx=" + mx + "&ttl=" + ttl],
                end: function () {
                    window.location.reload();
                }
            })
        }

        // 暂停解析
        function setRecordStatus(obj) {
            var domain = $("#domainInput").val();
            var thisObj = $(obj);
            var trObj = thisObj.parent().parent().parent();
            var name = trObj.find("td:eq(1)").text();       // eq()索引是从0开始计算
            var status = trObj.find("td:eq(7)").text();

            var url = "{% url 'ssl_cert:set_record_status' %}";
            var data = {
                "domain": domain,
                "name": name,
                "status": status === "正常" ? "disable" : "enable",
                "csrfmiddlewaretoken": "{{ csrf_token }}",
            };

            layer.load(0, {shade: false}); // loading 加载层, 0代表加载的风格，支持0-2
            $.post(url, data, function (result) {
                layer.closeAll('loading');  // 关闭loading 加载层
                if (result["status"] === "success") {
                    layer.alert("操作成功", {
                        icon: 1, end: function () {
                            window.location.reload();
                        }
                    });
                } else {
                    layer.alert("操作失败", {icon: 2});
                }
            });
        }

        // 删除记录
        function deleteRecord(obj) {
            var domain = $("#domainInput").val();
            var thisObj = $(obj);
            var trObj = thisObj.parent().parent().parent();
            var name = trObj.find("td:eq(1)").text();       // eq()索引是从0开始计算

            var url = "{% url 'ssl_cert:delete_record' %}";
            var data = {
                "domain": domain,
                "name": name,
                "csrfmiddlewaretoken": "{{ csrf_token }}",
            };

            layer.confirm("确定删除 " + name + " 记录吗?", {btn: ["确定", "取消"]},
                function () {
                    layer.load(0, {shade: false}); // loading 加载层, 0代表加载的风格，支持0-2
                    $.post(url, data, function (result) {
                        layer.closeAll('loading');  // 关闭loading 加载层
                        if (result["status"] === "success") {
                            layer.alert("删除成功", {
                                icon: 1, end: function () {
                                    window.location.reload();
                                }
                            });
                        } else {
                            layer.alert("删除失败", {icon: 2});
                        }
                    })
                },
                function () {
                    // 取消按钮，不需任何操作
                }
            );

        }
    </script>
{% endblock %}