apps/ssl_cert/urls.py
from django.urls import path
from . import views
from . import custom_domain_menu_views

app_name = 'ssl_cert'
urlpatterns = [
    path('domain_list/', views.domain_list, name="domain_list"),
    path('create/', views.CreateSSLCertView.as_view(), name="create"),
    path('batch_create/', views.BatchCreateSslCertView.as_view(), name="batch_create"),
    path('upload_ssl_cert/', views.UploadSSLCertView.as_view(), name="upload_ssl_cert"),
    path('view_ssl_cert/', views.ViewSSLCertView.as_view(), name="view_ssl_cert"),
    path('download_file/', views.DownloadFileView.as_view(), name="download_file"),
    path('update_ssl_cert/', views.UpdateSSLCertView.as_view(), name="update_ssl_cert"),
    path('disable_ssl_cert/', views.DisableSSLCertView.as_view(), name="disable_ssl_cert"),
    path('delete_ssl_cert/', views.DeleteSSLCertView.as_view(), name="delete_ssl_cert"),
    path('sync_sub_domains/', views.SyncSubDomainView.as_view(), name="sync_sub_domains"),
    path('sub_domains/', views.SubDomainsView.as_view(), name="sub_domains"),
    path('dns/', views.DnsView.as_view(), name="dns"),
    path('to_email/', views.ToEmailView.as_view(), name="to_email"),
    path('source_ip/', views.SourceIPView.as_view(), name="source_ip"),
    path('send_ssl_cert_to_email/', views.SendSSLCertView.as_view(), name="send_ssl_cert_to_email"),
    path('add_record/', views.AddRecordView.as_view(), name="add_record"),
    path('modify_record/', views.ModifyRecordView.as_view(), name="modify_record"),
    path('set_record_status/', views.SetRecordStatusView.as_view(), name="set_record_status"),
    path('delete_record/', views.DeleteRecordView.as_view(), name="delete_record"),

    path('check_domain_status/', views.CheckDomainStatusView.as_view(), name="check_domain_status"),

    path('custom_domain/', custom_domain_menu_views.CustomDomainViews.as_view(), name="custom_domain"),
    path('custom_domain_list/', custom_domain_menu_views.custom_domain_list, name="custom_domain_list"),
    path('add_custom_domain/', custom_domain_menu_views.AddCustomDomainView.as_view(), name="add_custom_domain"),
    path('delete_custom_domain/', custom_domain_menu_views.DeleteCustomDomainView.as_view(),
         name="delete_custom_domain"),
    path('to_email_custom_domain/', custom_domain_menu_views.CustomDomainToEmailView.as_view(),
         name="to_email_custom_domain"),
]

apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('activate/<str:code>/', views.Activate.as_view(), name="activate"),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('settings/', views.Setting.as_view(), name="settings"),
    path('user_center/', views.UserCenter.as_view(), name="user_center"),
    path('user_list/', views.UserListView.as_view(), name="user_list"),
    path('is_superuser/', views.IsSuperUser.as_view(), name="is_superuser"),
    path('create_user/', views.CreateUserView.as_view(), name="create_user"),
    path('delete_user/', views.UserDeleteView.as_view(), name="delete_user"),
    path('user_bind_domain/', views.UserBindDomain.as_view(), name="user_bind_domain"),
    path('password_change/', views.PasswordChangeView.as_view(), name="password_change"),

    path('email_config/', views.EmailConfigView.as_view(), name="email_config"),
]

new_ssl_cert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from ssl_cert.views import IndexView
# from users import views

urlpatterns = [
    path('ssl-cert-admin/', admin.site.urls),

    path('index/', IndexView.as_view(), name="index"),
    path('', RedirectView.as_view(url='index/')),
    path('ssl/', include("ssl_cert.urls")),
    path('users/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    # path('ajax_captcha/', views.ajax_captcha, name='ajax_captcha'),
]

templates/base-layer.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {#    <title>Title</title>#}
    <link rel="stylesheet" href="{% static 'layui/layui/css/layui.css' %}">

    {% block css %}
    {% endblock %}
</head>
<body style="margin-top: 20px;">

{% block main %}
{% endblock %}

<script src="{% static 'bootstrap/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'layui/layui/layui.js' %}"></script>

{% block javascripts %}
{% endblock %}
</body>
</html>

templates/base-menu.html
{% extends 'bash-head-footer.html' %}

{% load static %}


{% block main %}
    <div class="fly-panel">
        <div class="layui-container">
            <ul class="layui-nav layui-clear" lay-filter="" style="background-color: white; padding-left: 0px">
                <li class="layui-nav-item" id="menuIndex"><a href="{% url 'index' %}" style="color: black">首页</a></li>

                <li class="layui-nav-item" id="customDomainMenuIndex"><a href="{% url 'ssl_cert:custom_domain' %}" style="color: black">自定义域名</a></li>
{#                <li class="layui-nav-item" style="margin-left: 10px" id="menuSSL">#}
{#                    <a href="javascript:;" style="color: black;">证书</a>#}
{#                    <dl class="layui-nav-child"> <!-- 二级菜单 -->#}
{#                        <dd id="menuCreateSslCert"><a href="#">创建证书</a></dd>#}
{#                        <dd><a href="">批量创建证书</a></dd>#}
{#                        <dd><a href="">上传证书</a></dd>#}
{#                    </dl>#}
{#                </li>#}
{#                <li class="layui-nav-item" style="margin-left: 20px">#}
{#                    <a href="javascript:;" style="color: black">域名</a>#}
{#                    <dl class="layui-nav-child"> <!-- 二级菜单 -->#}
{#                        <dd><a href="">查看子域名</a></dd>#}
{#                        <dd><a href="">添加解析记录</a></dd>#}
{#                    </dl>#}
{#                </li>#}



            </ul>
        </div>
    </div>

    {% block content %}
    {% endblock %}

{% endblock %}

templates/bash-head-footer.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>SSL证书管理</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="keywords" content="SSL证书管理">
    <meta name="description" content="创建证书、证书管理、域名管理">

    <link rel="stylesheet" href="{% static 'layui/layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'layui/css/global.css' %}">


    <style>
        .layui-nav .layui-nav-more {
            content: '';
            width: 0;
            height: 0;
            border-style: solid dashed dashed;
            border-color: black transparent transparent;
            overflow: hidden;
            cursor: pointer;
            transition: all .2s;
            -webkit-transition: all .2s;
            position: absolute;
            top: 50%;
            right: 3px;
            margin-top: -3px;
            border-width: 6px;
            border-top-color: rgba(255, 255, 255, .7);
            border-top-color: black;
        }

        .layui-nav .layui-nav-mored {
            margin-top: -9px;
            border-style: dashed dashed solid;
            border-color: transparent transparent #000000;
        }
    </style>

    {% block css %}
    {% endblock %}
</head>
<body>

<div class="fly-header layui-bg-black">
    <div class="layui-container">
        <a class="fly-logo" href="{% url 'index' %}">
            <img src="{% static 'images/logo.svg' %}" alt="logo" width="135px" height="37px">
        </a>
        <ul class="layui-nav fly-nav-user">
            <li class="layui-nav-item" id="showtime" style="color: rgba(255,255,255,.7); margin-right: 20px;"></li>

            {% if user.is_authenticated %}
                <!-- 登入后的状态 -->
                <li class="layui-nav-item">
                    <a class="fly-nav-avatar" href="javascript:;">
                        <cite class="layui-hide-xs">{{ user.username }}</cite>
                        <i class="iconfont icon-renzheng layui-hide-xs" title="用户"></i>
                        <img src="{% static 'layui/images/avatar/0.jpg' %}">
                    </a>
                    <dl class="layui-nav-child">
                        {% if user.is_superuser %}
                            <dd><a href="{% url 'users:user_center' %}"><i class="layui-icon">&#xe620;</i>设置</a></dd>
                            <hr style="margin: 5px 0;">
                        {% endif %}
                        <dd><a href="{% url 'users:logout' %}" style="text-align: center;">退出</a></dd>
                    </dl>
                </li>
            {% else %}
                <!-- 未登入的状态 -->
                <li class="layui-nav-item">
                    <a class="iconfont icon-touxiang layui-hide-xs" href="{% url 'users:login' %}"></a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'users:login' %}">登入</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{% url 'users:register' %}">注册</a>
                </li>
            {% endif %}

        </ul>
    </div>
</div>


{% block main %}
{% endblock %}


<div class="fly-footer">
    <p>Powered by zhenfeng.zhao © 2019</p>
</div>

<script src="{% static 'bootstrap/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'layui/layui/layui.js' %}"></script>
<script src="{% static 'js/showtime.js' %}"></script>
<script>
    layui.cache.page = '';
    layui.cache.user = {
        username: '游客'
        , uid: -1
        {#, avatar: '../static/layui/images/avatar/00.jpg'#}
        , avatar: '{% static "layui/images/avatar/00.jpg" %}'
        , experience: 83
        , sex: '男'
    };
    layui.config({
        version: "3.0.0"
        {#, base: '../static/layui/mods/' //这里实际使用时，建议改成绝对路径#}
        , base: '{% static "layui/mods/" %}' //这里实际使用时，建议改成绝对路径
    }).extend({
        fly: 'index'
    }).use('fly');
</script>

{% block js %}
{% endblock %}

{#<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");#}
{#document.write(unescape("%3Cspan id='cnzz_stat_icon_30088308'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "w.cnzz.com/c.php%3Fid%3D30088308' type='text/javascript'%3E%3C/script%3E"));</script>#}
</body>
</html>