apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('activate/<str:code>/', views.Activate.as_view(), name="activate"),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('settings/', views.Setting.as_view(), name="settings"),
    path('user_center/', views.UserCenter.as_view(), name="user_center"),
    path('user_list/', views.UserListView.as_view(), name="user_list"),
    path('is_superuser/', views.IsSuperUser.as_view(), name="is_superuser"),
    path('create_user/', views.CreateUserView.as_view(), name="create_user"),
    path('delete_user/', views.UserDeleteView.as_view(), name="delete_user"),
    path('user_bind_domain/', views.UserBindDomain.as_view(), name="user_bind_domain"),
    path('password_change/', views.PasswordChangeView.as_view(), name="password_change"),

    path('email_config/', views.EmailConfigView.as_view(), name="email_config"),
]

new_ssl_cert/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from ssl_cert.views import IndexView
# from users import views

urlpatterns = [
    path('ssl-cert-admin/', admin.site.urls),

    path('index/', IndexView.as_view(), name="index"),
    path('', RedirectView.as_view(url='index/')),
    path('ssl/', include("ssl_cert.urls")),
    path('users/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    # path('ajax_captcha/', views.ajax_captcha, name='ajax_captcha'),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ssl_cert.models import Domain


# Create your models here.


class User(AbstractUser):
    """
    用户
    """
    email = models.EmailField(unique=True)
    # is_active = models.BooleanField(default=False)
    domain = models.ManyToManyField(Domain, verbose_name="域名", blank=True)

    class Meta(AbstractUser.Meta):
        pass


class ActivateCode(models.Model):
    """
    激活码
    """
    user = models.ForeignKey(User, verbose_name="用户", on_delete=models.CASCADE)
    code = models.CharField(verbose_name="激活码", max_length=255)
    expire_time = models.DateTimeField(verbose_name="过期时间")
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    update_time = models.DateTimeField(verbose_name="更新时间", auto_now=True)

    class Meta:
        ordering = ("-id",)
        verbose_name = "激活码"
        verbose_name_plural = verbose_name


class EmailConfig(models.Model):
    """
    email 服务器配置
    """
    email = models.EmailField(verbose_name="邮箱", max_length=100)
    password = models.CharField(verbose_name="密码", max_length=20)
    server = models.CharField(verbose_name="服务器", max_length=50)
    port = models.CharField(verbose_name="端口", default=465, max_length=4)
    ssl = models.BooleanField(verbose_name="SSL加密", default=True)

    class Meta:
        verbose_name = "邮箱配置"
        verbose_name_plural = verbose_name

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model
# from .models import User
from captcha.fields import CaptchaField
from .models import EmailConfig

User = get_user_model()


class RegisterForm(UserCreationForm):
    """
    用户注册
    """
    # 验证码
    captcha = CaptchaField(error_messages={"invalid": "验证码错误", "required": "请输入验证码"})

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password1", "password2", "email", "captcha")


# class RegisterForm(forms.ModelForm):
#     username = forms.CharField(
#         required=True,
#         min_length=3,
#         max_length=16,
#         error_messages={
#             "required": "用户名不能为空",
#             "min_length": "用户名最少3位字符",
#             "max_length": "用户名最大16个字符",
#         }
#     )
#     password1 = forms.CharField(
#         required=True,
#         min_length=6,
#         max_length=16,
#         error_messages={
#             "required": "密码不能为空",
#             "min_length": "密码长度最少6位",
#         }
#     )
#     password2 = forms.CharField(
#         required=True,
#         min_length=6,
#         max_length=16,
#         error_messages={
#             "required": "密码不能为空",
#             "min_length": "密码长度最少6位",
#         }
#     )
#
#     class Meta:
#         model = User
#         fields = ("username", "password1", "password2", "email")
#
#         error_messages = {
#             "username": {"required": "用户名不能为空"},
#             "email": {"required": "邮箱不能为空"},
#         }
#
#     def clean(self):
#         cleaned_data = super().clean()
#         username = cleaned_data.get("username")
#         email = cleaned_data.get("email")
#         password1 = cleaned_data.get("password1")
#         password2 = cleaned_data.get("password2")
#
#         if User.objects.filter(username=username).count():
#             raise forms.ValidationError('用户名：{}已存在'.format(username))
#
#         if password1 != password2:
#             raise forms.ValidationError("两次密码输入不一致")
#
#         if User.objects.filter(email=email).count():
#             raise forms.ValidationError('邮箱：{}已存在'.format(email))


class LoginForm(forms.Form):
    """
    用户登陆
    """
    username = forms.CharField(required=True, error_messages={"required": "用户名不能为空"})
    password = forms.CharField(required=True, error_messages={"required": "密码不能为空"})
    # 验证码
    captcha = CaptchaField(error_messages={"invalid": "验证码错误", "required": "请输入验证码"})


class CreateUserForm(UserCreationForm):
    """
    用于管理员创建普通用户
    """

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "password1", "password2", "email")


class PasswordChangeForm(forms.Form):
    """
    修改密码
    """
    password1 = forms.CharField(
        required=True,
        min_length=6,
        max_length=16,
        error_messages={
            "required": u"密码不能为空"
        })

    password2 = forms.CharField(
        required=True,
        min_length=6,
        max_length=16,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password1")
        confirm_password = cleaned_data.get("password2")
        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class EmailConfigForm(forms.ModelForm):
    class Meta:
        model = EmailConfig
        fields = ['email', 'password', 'server', 'port', 'ssl']

apps/users/views.py
import re
import datetime
import uuid
import json
from threading import Thread
import logging
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import auth
from django.core.mail import EmailMultiAlternatives
from django.http import JsonResponse
from django.views.generic.base import View, TemplateView
from django.contrib.auth.hashers import make_password
from django.shortcuts import get_object_or_404
from django.contrib.auth import update_session_auth_hash
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import RegisterForm, PasswordChangeForm, LoginForm, CreateUserForm, EmailConfigForm
from .models import User, ActivateCode, EmailConfig
from django.conf import settings
from ssl_cert.models import Domain
from apps.mixin import LoginRequiredMixin
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url

log = logging.getLogger('django')


# Create your views here.


class Activate(View):
    def get(self, request, code):
        query = ActivateCode.objects.filter(code=code, expire_time__gte=datetime.datetime.now())
        if query.count() > 0:
            code_record = query[0]
            code_record.user.is_active = True
            code_record.user.save()
            return render(request, "users/login.html", {"msg": "激活成功,请登陆", "status": "success"})
        else:
            return render(request, "users/login.html", {"msg": "激活失败"})


# def ajax_captcha(request):
#     """
#     验证码输入验证
#     """
#     if request.is_ajax():
#         result = CaptchaStore.objects.filter(response=request.GET.get('response'), hashkey=request.GET.get('hashkey'))
#         if result:
#             data = {'status': 1}
#         else:
#             data = {'status': 0}
#         return JsonResponse(data)


# class Register(View):
#     """
#     用户注册
#     """
#
#     def get(self, request):
#         redirect_to = request.POST.get('next', request.GET.get('next', ''))
#         form = RegisterForm()
#         return render(request, 'users/register.html', context={'form': form, 'next': redirect_to})
#
#     def post(self, request):
#         redirect_to = request.POST.get('next', request.GET.get('next', ''))
#         # 提交的是用户名（username）、密码（password）、邮箱（email）
#         form = RegisterForm(request.POST)
#         # 验证数据的合法性
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.is_active = False
#             user.save()
#
#             activate_code = str(uuid.uuid4()).replace("-", "")
#             expire_time = datetime.datetime.now() + datetime.timedelta(days=2)
#             ActivateCode(user=user, code=activate_code, expire_time=expire_time).save()
#
#             activate_link = "http://%s/users/activate/%s" % (request.get_host(), activate_code)
#             subject = '[SSL证书管理] 账号激活'
#             message = F'注册用户名为: {user.username}, 点击<a href="{activate_link}">请这里</a>激活。<br><br>或复制激活链接至浏览器地址栏中激活账号: {activate_link}'
#             from_email = settings.DEFAULT_FROM_EMAIL
#             recipient_list = [user.email]
#             msg = EmailMultiAlternatives(subject, message, from_email, recipient_list)
#             msg.content_subtype = 'html'
#             Thread(target=msg.send).start()
#             log.info(F"账号: {user.username} 注册成功，已发送激活邮件至: {user.email}")
#
#             return render(request, 'users/login.html',
#                           {"msg": "注册成功，激活邮件已经发送到您的邮箱，请点击邮箱中的激活链接完成激活。"})
#
#         return render(request, 'users/register.html', context={'form': form, 'next': redirect_to})


class Register(CreateView):
    template_name = "users/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        human = True  # 验证码
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # 发送注册邮件
        self.send_email(user, self.request.get_host())
        msg = "注册成功，激活邮件已经发送到您的邮箱，请前往邮箱完成激活。"
        # return super().form_valid(form)

        context = self.get_context_data()
        context["msg"] = msg
        context["status"] = "success"
        return render(self.request, 'users/login.html', context=context)

    def get_context_data(self, **kwargs):
        # 获取原有的上下文
        context = super().get_context_data(**kwargs)
        # 增加新上下文
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        context['hashkey'] = hashkey
        context['image_url'] = image_url

        return context

    def send_email(self, user, host):
        activate_code = str(uuid.uuid4()).replace("-", "")
        expire_time = datetime.datetime.now() + datetime.timedelta(days=2)
        ActivateCode(user=user, code=activate_code, expire_time=expire_time).save()

        activate_link = "http://%s/users/activate/%s" % (host, activate_code)
        subject = '[SSL证书管理] 账号激活'
        message = F'注册用户名为: {user.username}, 点击<a href="{activate_link}">请这里</a>激活。<br><br>或复制激活链接至浏览器地址栏中激活账号: {activate_link}'
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [user.email]
        msg = EmailMultiAlternatives(subject, message, from_email, recipient_list)
        msg.content_subtype = 'html'
        Thread(target=msg.send).start()
        log.info(F"账号: {user.username} 注册成功，已发送激活邮件至: {user.email}")


class Login(View):
    """
    登陆
    """

    def get(self, request):
        redirect_to = request.POST.get('next', request.GET.get('next', ''))
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        return render(request, 'users/login.html',
                      context={'next': redirect_to, "hashkey": hashkey, "image_url": image_url})

    def post(self, request):
        redirect_to = request.POST.get('next', request.GET.get('next', ''))
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        form = LoginForm(request.POST)
        if form.is_valid():
            human = True  # 验证码
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # 检查账号是否存在
            user_exists = User.objects.filter(username=username).first()
            if user_exists is not None:
                # 检查账号的密码是否正确
                user = auth.authenticate(username=username, password=password)
                if user is not None:
                    # 检查账号是否激活
                    if user.is_active:
                        auth.login(request, user)
                        if redirect_to:
                            return redirect(redirect_to)
                        else:
                            return redirect(reverse('index'))
                    else:
                        msg = "账户未激活"
                else:
                    msg = "账号或密码错误"
            else:
                msg = "账号不存在"
            return render(request, 'users/login.html', context={
                'next': redirect_to,
                "msg": msg,
                "username": username,
                "hashkey": hashkey,
                "image_url": image_url
            })
        else:
            pattern = '<li>.*?<ul class=.*?><li>(.*?)</li>'
            errors = str(form.errors)
            form_errors = re.findall(pattern, errors)
            return render(request, 'users/login.html', context={
                'username': request.POST.get('username'),
                "hashkey": hashkey,
                "image_url": image_url,
                "msg": form_errors[0],
            })


class Logout(LoginRequiredMixin, View):
    """退出登陆"""

    def get(self, request):
        auth.logout(request)
        return redirect(reverse('users:login'))


# TODO 功能暂未开发
class Setting(LoginRequiredMixin, TemplateView):
    """
    基础设置
    """
    template_name = "users/settings/general_settings.html"


class UserCenter(LoginRequiredMixin, TemplateView):
    """
    用户中心:
        创建新用户
        删除用户:   单个删除/批量删除
        修改账号类型: 管理员/普通账号
        修改密码
    """
    template_name = "users/settings/user_center.html"


class UserListView(LoginRequiredMixin, View):
    """用户列表"""

    def get(self, request):
        page = request.GET.get('page')
        limit = request.GET.get('limit', 10)
        search_content = request.GET.get('userSearch', "")
        query = User.objects.filter(Q(username__contains=search_content) | Q(email__contains=search_content)).order_by(
            '-id')
        paginator = Paginator(query, limit)
        count = query.count()

        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # 如果请求的页数不是整数，返回第一页。
            contacts = paginator.page(1)
        except EmptyPage:
            # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
            contacts = paginator.page(paginator.num_pages)

        fields = ['id', 'username', 'email', 'is_active', 'is_superuser']
        data = {
            "code": 0,
            "msg": "",
            "count": count,
            "data": list(contacts.object_list.values(*fields)),
        }

        return JsonResponse(data)


class IsSuperUser(LoginRequiredMixin, View):
    """
    设置用户为管理员或者普通用户
    """

    def post(self, request):
        pk = request.POST.get('id')
        user_obj = User.objects.get(id=pk)
        if user_obj.is_superuser:
            user_obj.is_superuser = False
        else:
            user_obj.is_superuser = True
        user_obj.save()
        return JsonResponse({"status": "success"})


class CreateUserView(LoginRequiredMixin, View):
    """创建用户"""

    def get(self, request):
        return render(request, 'users/settings/user_create.html')

    def post(self, request):
        log.info(F"create new user: {request.POST}")
        form = CreateUserForm(request.POST)
        if form.is_valid():

templates/users/settings/base-settings.html
{% extends 'bash-head-footer.html' %}

{% block main %}
    <div class="layui-container fly-marginTop fly-user-main">
        <ul class="layui-nav layui-nav-tree layui-inline" lay-filter="user">
            <li class="layui-nav-item">
                <a href="{% url 'users:user_center' %}">
                    <i class="layui-icon">&#xe612;</i>
                    用户中心
                </a>
            </li>
            <li class="layui-nav-item">
                <a href="{% url 'users:settings' %}">
                    <i class="layui-icon">&#xe620;</i>
                    基本设置
                </a>
            </li>
        </ul>

        <div class="site-tree-mobile layui-hide">
            <i class="layui-icon">&#xe602;</i>
        </div>
        <div class="site-mobile-shade"></div>

        <div class="site-tree-mobile layui-hide">
            <i class="layui-icon">&#xe602;</i>
        </div>
        <div class="site-mobile-shade"></div>

        {% block settings_content %}
        {% endblock %}
    </div>

{% endblock %}

templates/users/settings/user_center.html
{% extends 'users/settings/base-settings.html' %}

{% load static %}

{% block css %}
{% endblock %}

{% block settings_content %}
    <div class="layui-container fly-marginTop fly-user-main">
        <div class="fly-panel fly-panel-user" pad20>
            <div class="layui-tab layui-tab-brief" lay-filter="user">
                <ul class="layui-tab-title" id="LAY_mine">
                    <li data-type="mine-jie" lay-id="index" class="layui-this">用户管理</li>
                </ul>
                <div class="layui-tab-content" style="padding: 10px 0;">
                    <div class="layui-btn-group btnGroup">
                        <button type="button" id="btnCreate" class="layui-btn layui-btn-sm">
                            <i class="layui-icon">&#xe608;</i>新增
                        </button>
                        <button type="button" id="btnDelete" class="layui-btn layui-btn-sm" data-type="batchDelete">
                            <i class="layui-icon">&#xe640;</i>删除
                        </button>
                        {#                        <button type="button" id="btnEnable" class="layui-btn layui-btn-sm">#}
                        {#                            <i class="layui-icon">&#xe605;</i>启用#}
                        {#                        </button>#}
                        {#                        <button type="button" id="btnDisable" class="layui-btn layui-btn-sm">#}
                        {#                            <i class="layui-icon">&#x1007;</i>禁用#}
                        {#                        </button>#}
                    </div>

                    <div class="userSearchTable" style="float: right">
                        <div class="layui-inline">
                            <input class="layui-input" name="id" id="userTableReload" autocomplete="off"
                                   placeholder="用户名 / 邮箱">
                        </div>
                        <button class="layui-btn" data-type="reload">搜索</button>
                    </div>
                    <br>

                    <table class="layui-hide" id="userTable" lay-filter="userFilter"></table>

                    <script type="text/html" id="barUser">
                        {#授权按钮，此功能未启用#}
                        {#<a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="authorization"><i#}
                        {#        class="layui-icon">&#xe716;</i></a>#}
                        <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="password"><i class="layui-icon">&#xe673;</i></a>
                        <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="delete"><i class="layui-icon">&#xe640;</i></a>
                    </script>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $(".fly-marginTop ul li:first").addClass("layui-this");
        })
    </script>

    <script>
        // 自定义字符格式化
        // 使用方法: var a = "abcd {0},{}".format('中', '国'); console.log(a)
        String.prototype.format = function () {
            if (arguments.length === 0) return this;
            var param = arguments[0], str = this;
            if (typeof (param) === 'object') {
                for (var key in param)
                    str = str.replace(new RegExp("\\{" + key + "\\}", "g"), param[key]);
                return str;
            } else {
                for (var i = 0; i < arguments.length; i++)
                    str = str.replace(new RegExp("\\{" + i + "\\}", "g"), arguments[i]);
                return str;
            }
        };

        layui.use(['table'], function () {
            var table = layui.table
                , form = layui.form;

            table.render({
                elem: '#userTable'
                , url: "{% url 'users:user_list' %}"
                , cellMinWidth: 80
                , cols: [[
                    {type: 'numbers'}
                    , {type: 'checkbox', field: 'id'}
                    , {field: 'username', title: '用户名', align: 'center'}
                    , {field: 'email', title: "邮箱", align: 'center', minWidth: 200,}
                    , {
                        field: 'is_active', title: '状态', width: 80, align: 'center', templet: function (d) {
                            if (d.is_active) {
                                return "启用";
                            } else {
                                return "禁用";
                            }
                        }
                    }
                    // 显示 普通账号和管理员账号，此功能未启用
                    //, {
                    //    field: 'is_superuser', title: '类型', width: 120, sort: true, align: 'center',
                    //    templet: function (d) {
                    //        if (d.username === "admin") {
                    //            return '<input type="checkbox" checked name="管理员" lay-skin="switch" lay-text="管理员|普通账号" lay-filter="isSuperuser" disabled>'
                    //        }
                    //        if (d.is_superuser) {
                    //            if (d.username === "{{ request.user }}") {
                    //                return '<input type="checkbox" checked name="管理员" lay-skin="switch" lay-text="管理员|普通账号" lay-filter="isSuperuser" disabled>'
                    //            } else {
                    //                return '<input type="checkbox" checked name="管理员" value="{0}" lay-skin="switch" lay-text="管理员|普通账号" lay-filter="isSuperuser">'.format(d.id)
                    //            }
                    //        } else {
                    //            if (d.username === "{{ request.user }}") {
                    //                return '<input type="checkbox" name="管理员" lay-skin="switch" lay-text="管理员|普通账号" lay-filter="isSuperuser" disabled>'
                    //            }
                    //            return '<input type="checkbox" name="管理员" value="{0}" lay-skin="switch" lay-text="管理员|普通账号" lay-filter="isSuperuser">'.format(d.id)
                    //        }
                    //    }
                    //}
                    , {fixed: 'right', title: '操作', align: 'center', toolbar: "#barUser"}
                ]]
                , page: true
                , id: 'userReload'
            });

            //
            var $ = layui.$, active = {
                reload: function () {           // 表格重载（用户搜索）
                    var userTableReload = $('#userTableReload');
                    //执行重载
                    table.reload('userReload', {
                        page: {
                            curr: 1 //重新从第 1 页开始
                        }
                        , where: {
                            userSearch: userTableReload.val(),
                        }
                    }, 'data');
                },
                batchDelete: function () {      // 批量删除
                    var checkStatus = table.checkStatus('userReload')
                        , deleteData = checkStatus.data;

                    if (deleteData.length === 0) {
                        layer.msg("请选择要删除的用户");
                        return
                    }

                    // 不能删除 admin 用户，不能自己删除自己的账号
                    var cur_user = "{{ request.user }}";
                    for (var i = 0; i < deleteData.length; i++) {
                        if (deleteData[i]["username"] === "admin") {
                            layer.msg("不能删除admin用户");
                            return
                        } else if (deleteData[i]["username"] === cur_user) {
                            layer.msg("自己不能删除自己的账号");
                            return
                        }
                    }

                    var data = {
                        "deleteData": JSON.stringify(deleteData),
                        "csrfmiddlewaretoken": "{{ csrf_token }}",
                    };
                    {#layer.alert(JSON.stringify(data));#}
                    //
                    layer.confirm('确定删除吗？', function (index) {
                        var url = "{% url 'users:delete_user' %}";
                        $.post(url, data, function (result) {
                            if (result["status"] === "success") {
                                layer.alert("用户已删除", {icon: 1}, function (index) {
                                    window.location.reload();
                                });
                            } else {
                                layer.alert("用户删除失败");
                            }
                        });
                        layer.close(index);
                    });
                    //
                }
            };

            $('.userSearchTable .layui-btn').on('click', function () {      // 表格重载（用户搜索）
                var type = $(this).data('type');
                active[type] ? active[type].call(this) : '';
            });

            $('.btnGroup .layui-btn').on('click', function () {             // 批量删除
                var type = $(this).data('type');
                active[type] ? active[type].call(this) : '';
            });

            // 将用户设置为管理员或者普通账号接口，此功能未启用
            // 监听 将用户设置为管理员 操作
            //form.on('switch(isSuperuser)', function (obj) {
            //    {#layer.tips(this.value + ' ' + this.name + '：' + obj.elem.checked, obj.othis);#}
            //    var url = "{% url 'users:is_superuser' %}";
            //    var data = {
            //        "id": this.value,
            //        "csrfmiddlewaretoken": "{{ csrf_token }}",
            //    };
            //    $.post(url, data, function (result) {
            //        if (result["status"] === "success") {
            //            layer.msg("权限已修改")
            //        } else {
            //            layer.alert("未知错误，请检查")
            //        }
            //    })
            //});


            // 创建用户
            $("#btnCreate").click(function () {
                layer.open({
                    type: 2,
                    title: '新增',
                    shadeClose: true,
                    maxmin: true,
                    area: ['500px', '350px'],
                    content: '{% url 'users:create_user' %}',
                    end: function () {
                        //关闭时做的事情
                        location.reload();
                    }
                });
                // 全屏
                {#div = layer.open();#}
                {#layer.full(div)#}
            });

            //监听工具条（操作列的按钮）
            table.on('tool(userFilter)', function (obj) {
                var data = obj.data;
                if (obj.event === 'authorization') {                // 授权接口，此功能未启用
                    layer.open({
                        type: 2,
                        title: '授权',
                        shadeClose: true,
                        maxmin: true,
                        area: ['550px', '550px'],
                        content: ["{% url 'users:user_bind_domain' %}" + "?id=" + data.id, "no"],
                    })
                } else if (obj.event === "password") {              // 修改密码
                    layer.open({
                        type: 2,
                        title: '修改密码',
                        shadeClose: false,
                        maxmin: true,
                        area: ['500px', '350px'],
                        content: ["{% url 'users:password_change' %}" + '?id=' + data.id, 'no'],
                    });
                } else if (obj.event === 'delete') {                        // 和批量删除共用一个接口，所以格式按批量删除的格式提交
                    layer.confirm('确定删除吗？', function (index) {
                        var url = "{% url 'users:delete_user' %}";
                        var data = {
                            "deleteData": JSON.stringify([obj.data]),
                            "csrfmiddlewaretoken": "{{ csrf_token }}",
                        };
                        $.post(url, data, function (result) {
                            if (result["status"]) {
                                layer.alert('删除成功', {icon: 1});
                                obj.del();
                            } else {
                                layer.alert('删除失败', {icon: 5});
                            }
                        });
                        layer.close(index);
                    });
                } else if (obj.event === 'edit') {
                    layer.alert('编辑行：<br>' + JSON.stringify(data))
                }
            });


        });
    </script>


{% endblock %}